metrics: ["Recall","MRR","NDCG","Hit","Precision", "Serendipity","Novelty","AveragePopularity", "ItemCoverage", "Fidelity", "LIR", "LID", "SEP","SED","PTD", "PPT", "PTC", "LITD","SETD"] # (list or str) Evaluation metrics.
data_path: /home/recsysdatasets
eval_step: 5
batch_size: 2
eval_batch_size: 1
epochs: 5
save_dataloaders: True
save_dataset: True

learning_rate: 2e-4
weight_decay: 0.01
warmup_steps: 250               # (int) Number of warmup steps for learning rate scheduler.
embedding_size: 768             # (int) Size of the embeddings.
num_heads: 12                   # (int) Number of heads in the multi-head attention.
num_layers: 6                   # (int) Number of layers in the transformer.
use_kg_token_types: True        # (bool) Whether to use token types for the knowledge graph.

base_model: distilgpt2
sequence_postprocessor: Cumulative

path_sample_args:
    restrict_by_phase: False    # (bool) Whether to restrict the last item in the reasoning path by the used ids in the dataloader phase.
    return_dict_in_generate: True
    output_scores: True
#peek
#path_constraint: [
#  [[null, 'user'], ["[UI-Relation]","entity"], ["[UI-Relation]","user"],["[UI-Relation]","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["0","entity"],["0_r","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["1","entity"],["1_r","entity"]],
#]

#mooccube
#path_constraint: [
#  [[null, 'user'], ["[UI-Relation]","entity"], ["[UI-Relation]","user"],["[UI-Relation]","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["covers_in_concept","entity"],["covers_in_concept_r","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["taught_by_instructor","entity"],["taught_by_instructor_r","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["Held_by_EducationalOrganization","entity"],["Held_by_EducationalOrganization_r","entity"]],
#]
#mooper
#path_constraint: [
#  [[null, 'user'], ["[UI-Relation]","entity"], ["[UI-Relation]","entity"],["[UI-Relation]","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["covers_in_concept","entity"],["covers_in_concept_r","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["includes_in_learningresources","entity"],["includes_in_learningresources_r","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["taught_by_instructor","entity"],["taught_by_instructor_r","entity"]],
#]

##coco
#path_constraint: [
#  [[null, 'user'], ["[UI-Relation]","entity"], ["[UI-Relation]","user"],["[UI-Relation]","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["belong_to_category","entity"],["belong_to_category_r","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["covers_in_concept","entity"],["covers_in_concept_r","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["taught_in_level","entity"],["taught_in_level_r","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["taught_in_language","entity"],["taught_in_language_r","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["has_target_audience","entity"],["has_target_audience_r","entity"]],
#  [[null, 'user'], ["[UI-Relation]","entity"], ["taught_by_instructor","entity"],["taught_by_instructor_r","entity"]],
#]